statefulSet:
  serviceName: service
  serviceAccountName: service-account
  replicas: 1
  containers:
    - name: redis
      image:
        repository: bitnami/redis
        tag: "7.0"
      ports:
        - name: redis
          containerPort: 6379
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 500m
          memory: 1024Mi
      envFromSecret:
        - secretName: auth-secret
          envs:
            - name: REDIS_PASSWORD
              key: PASSWORD
      volumeMounts:
        - name: storage
          mountPath: /bitnami/redis/data
          subPath: redis
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

serviceAccount:
  name: service-account

services:
  - name: service
    type: ClusterIP
    ports:
      - name: redis
        protocol: TCP
        port: 6379

vaultSecrets:
  - name: auth-secret
    path: secrets/redis
    templates:
      PASSWORD: "{% .Secrets.password %}"